version: '3'

services:
    
  db:
    container_name: lamp-dev_db
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: mysql_dev
     MYSQL_PASSWORD: mysql_dev
     MYSQL_USER: mysql_dev
    image: mariadb
    ports:
     - 3366:3306
    restart: always
    volumes:
     - data:/var/lib/mysql

  php:  
    container_name: lamp-dev_php
    image: bistormllc/php
    environment:
      DB_HOST: db
      DB_USER: mysql_dev
      DB_PASSWORD: mysql_dev
      DB_NAME: mysql_dev
      DB_DRIVER: mysql
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG: 1
      PHP_XDEBUG_IDEKEY: "vs-code"
      PHP_XDEBUG_REMOTE_HANDLER: "dbgp"
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0  # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "192.168.1.136" # Replace with your host IP address 
      PHP_XDEBUG_REMOTE_LOG: "/var/log/xdebug.log"
    volumes:
      - ./src:/var/www/html
    ports:
      - 9001:9000
    depends_on:
      - apache

  apache:
    container_name: lamp-dev_apache
    image: bistormllc/apache
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/zend_app/public
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
      - 8081:81

  adminer:
    container_name: lamp-dev_adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
    data:


