<div class="jumbotron">
    <h1>Notes</h1>
</div>
<?php
    $vars = $this->data[0];
    $themes = json_decode($vars['data'])->Themes;
?>
<div class="row">

    <div class="col-md-12">
        <div class="col-md-6">
            <div id="AddNote" class="panel panel-default">
                <div class="panel-heading active" role="tab" id="noteHeading">
                    <h3 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#AddNote"
                            href="#collapseNote" aria-expanded="true" aria-controls="collapseNote"
                           >Add a new note
                         </a>
                    </h3>
                </div>
                <div id="collapseNote" class="panel-collapse collapse in" role="tabpanel"
                    labelledby="noteHeading">
                    <div class="panel-body">
                        <form method="post" action="./note/add" id="note" name="AddNote" class="form-group">
                            <label for="title">Title</label>
                            <input class="form-control" type="text" name="title" id="title" value="Title"></input>
                            <br>
                            <label for="content">Content</label>
                            <textarea class="form-control" type="text" name="content" id="content" value="Content"></textarea>
                            <br>
                            <select name="theme" class="custom-select">
                                <option selected>Theme</option>
                                <?php
                                    foreach ($themes As $theme) {
                                        echo "<option value=" . $theme->Id . " name=" . $theme->Name . ">" . $theme->Name . "</option>";
                                    }
                                ?>
                            </select>
                            <p>
                                <button class="btn btn-success">Add Note</button>
                            </p>
                        </form>
                    </div>
                </div>

                
            </div>
        </div>
        <div class="col-md-6">
            <div id="addTheme" class="panel panel-default">
                <div class="panel-heading active" role="tab" id="themeHeading">
                    <h3 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#AddTheme"
                            href="#collapseTheme" aria-expanded="true" aria-controls="collapseTheme"
                           >Add a new theme
                         </a>
                    </h3>
                </div>
                <div id="collapseTheme" class="panel-collapse collapse in" role="tabpanel"
                    labelledby="themeeHeading">
                    <div class="panel-body">
                        <form method="post" action="./theme/add" id="theme" name="AddTheme" class="form-group">
                            <label for="name">Theme Name</label>
                            <input class="form-control" type="text" name="name" id="name" value="Theme <?php print_r(sizeof($themes)+1) ?>"></input>
                            <br>
                            <label for="height">Height (in px)</label>
                            <input class="form-control" type="text" name="height" id="height" value="250"></input>
                            <br>
                            <label for="width">Width (in px)</label>
                            <input class="form-control" type="text" name="width" id="width" value="250"></input>
                            <br>
                            <label for="bgColor">Background Color</label>
                            <input class="form-control" type="text" name="backgroundColor" id="bgColor" value="#FFFFFF"></input>
                            <br>
                            <label for="color">Text Color</label>
                            <input class="form-control" type="text" name="textColor" id="color" value="#000000"></input>
                            <br>
                            <button class="btn btn-success">Add Theme</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
