<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Notes')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/app.css'))
        ?>

        
    </head>
    <body>
        <div id="root"></div>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
        <?= $this->inlineScript()->appendFile('/js/bundle.js') ?>
    </body>
    <!-- Scripts -->
    
</html>
